# https://taskfile.dev

version: '3'

vars:
  README: Read the README!
  
dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "{{.README}}"
    silent: true
  talgen:
    dir: talos
    cmds:
      - talhelper genconfig
  argocd-deploy:
    dir: system
    cmds:
      - ansible-playbook bootstrap.yml -vvv
