# https://taskfile.dev

version: '3'

vars:
  README: Read the README!
  
dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "{{.README}}"
    silent: true
  talm:
    cmds:
      - talm
  argocd-deploy:
    cmds:
      - ansible-playbook bootstrap.yml -vvv
