# https://taskfile.dev

version: '3'

vars:
  README: Read the README!
  
dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "{{.README}}"
    silent: true
  talm:
    cmds:
      - talm
  argocd-deploy:
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
