argo-cd:
  server:
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/iamwacko/homelab-test
            revision: &revision main
            directories:
              - path: system/*
              - path: apps/*
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: *revision
